//! Tree-like structure for iced.
//!
//! In ENSnano, `ensnano_design` implements the structures defined here, and are instantiated in
//! `ensnano_gui`.

pub mod drag_drop_target;
pub mod element;
pub mod hoverable_container;
pub mod keyboard_priority;
pub mod tree;

use self::{
    drag_drop_target::DragIdentifier,
    element::OrganizerElement,
    keyboard_priority::PriorityRequest,
    tree::{GroupId, OrganizerTree},
};
use iced::widget::text_input;
use std::collections::BTreeMap;

/// Public messages generated by an Organizer.
#[derive(Clone, Debug)]
pub enum OrganizerMessage<E: OrganizerElement> {
    InternalMessage(OrganizerInternalMessage<E>),
    Selection(Vec<E::Key>, Option<GroupId>),
    Candidates(Vec<E::Key>),
    ElementUpdate(Vec<BTreeMap<E::Key, E>>),
    NewAttribute(E::Attribute, Vec<E::Key>),
    /// Publishing a new organizer tree.
    NewTree(OrganizerTree<E::Key>),
    /// A new group is created.
    NewGroup {
        group_id: GroupId,
        elements_selected: Vec<E::Key>,
        new_tree: OrganizerTree<E::Key>,
    },
    /// Taking or releasing keyboard priority.
    SetKeyboardPriority(PriorityRequest),
    /// Ask Iced application to focus on this element
    SetFocus(text_input::Id),
}

#[derive(Clone, Debug)]
pub enum OrganizerInternalMessage<E: OrganizerElement> {
    Expand {
        id: NodeId<E::AutoGroup>,
        expanded: bool,
    },
    NodeSelected {
        id: NodeId<E::AutoGroup>,
    },
    NodeHovered {
        id: NodeId<E::AutoGroup>,
        hovered_in: bool,
    },
    KeyHovered {
        key: E::Key,
        hovered_in: bool,
    },
    ElementSelected {
        key: E::Key,
    },
    Edit {
        id: NodeId<E::AutoGroup>,
    },
    StopEdit,
    NameInput {
        name: String,
    },
    /// Create a new group.
    NewGroup,
    AddSelectionToGroup {
        id: NodeId<E::AutoGroup>,
    },
    Delete {
        id: NodeId<E::AutoGroup>,
    },
    DragDropped(DragIdentifier<E::Key, E::AutoGroup>),
    Dragging(DragIdentifier<E::Key, E::AutoGroup>),
    AttributeSelected {
        attribute: E::Attribute,
        id: NodeId<E::AutoGroup>,
    },
}

type TreeId = Vec<usize>;

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
pub enum NodeId<AutoGroupId> {
    Tree(TreeId),
    Section(usize),
    AutoGroup(AutoGroupId),
}

impl<E: std::fmt::Debug> NodeId<E> {
    pub fn push(&mut self, x: usize) {
        if let Self::Tree(v) = self {
            v.push(x);
        } else {
            log::error!("Trying to push on {self:?}");
        }
    }
}

/// Shorthands to send internal messages.
// TODO: remove all the `pub` once OrganizerMessage is in ensnano_gui
impl<E: OrganizerElement> OrganizerMessage<E> {
    pub fn expand(id: NodeId<E::AutoGroup>, expanded: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Expand { id, expanded })
    }

    pub fn node_selected(id: NodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NodeSelected { id })
    }

    pub fn node_hovered(id: NodeId<E::AutoGroup>, hovered_in: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NodeHovered { id, hovered_in })
    }

    pub fn key_hovered(key: E::Key, hovered_in: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::KeyHovered { key, hovered_in })
    }

    pub fn edit(id: NodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Edit { id })
    }

    pub fn delete(id: NodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Delete { id })
    }

    pub fn name_input(name: String) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NameInput { name })
    }

    pub fn stop_edit() -> Self {
        Self::InternalMessage(OrganizerInternalMessage::StopEdit)
    }

    pub fn element_selected(key: E::Key) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::ElementSelected { key })
    }

    pub fn add_selection_to_group(id: NodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::AddSelectionToGroup { id })
    }

    pub fn new_group() -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NewGroup)
    }

    pub fn dragging(key: DragIdentifier<E::Key, E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Dragging(key))
    }

    pub fn drag_dropped(key: DragIdentifier<E::Key, E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::DragDropped(key))
    }

    pub fn attribute_selected(attribute: E::Attribute, id: NodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::AttributeSelected { attribute, id })
    }
}
