absolute-paths-max-segments = 3
doc-valid-idents = [
    "ENSnano",
    "..",      # appends the Clippy defaults to our identifiers 
]
inherent-impl-lint-scope = "module"
too-many-arguments-threshold = 11 # TODO: 6
