use super::{OrganizerNodeId, drag_drop_target::DragIdentifier};
use crate::keyboard_priority::PriorityRequest;
use ensnano_design::{
    design_element::{DesignElement, DesignElementKey, DnaAttribute},
    organizer_tree::{GroupId, OrganizerTree},
};
use iced::widget::text_input;
use std::collections::BTreeMap;

/// Public messages generated by an Organizer.
#[derive(Clone, Debug)]
pub enum OrganizerMessage {
    InternalMessage(OrganizerInternalMessage),
    Selection(Vec<DesignElementKey>, Option<GroupId>),
    Candidates(Vec<DesignElementKey>),
    ElementUpdate(Vec<BTreeMap<DesignElementKey, DesignElement>>),
    NewAttribute(DnaAttribute, Vec<DesignElementKey>),
    /// Publishing a new organizer tree.
    NewTree(OrganizerTree),
    /// A new group is created.
    NewGroup {
        group_id: GroupId,
        elements_selected: Vec<DesignElementKey>,
        new_tree: OrganizerTree,
    },
    /// Taking or releasing keyboard priority.
    SetKeyboardPriority(PriorityRequest),
    /// Ask Iced application to focus on this element
    SetFocus(text_input::Id),
}

#[derive(Clone, Debug)]
pub enum OrganizerInternalMessage {
    Expand {
        id: OrganizerNodeId,
        expanded: bool,
    },
    NodeSelected {
        id: OrganizerNodeId,
    },
    NodeHovered {
        id: OrganizerNodeId,
        hovered_in: bool,
    },
    KeyHovered {
        key: DesignElementKey,
        hovered_in: bool,
    },
    ElementSelected {
        key: DesignElementKey,
    },
    Edit {
        id: OrganizerNodeId,
    },
    StopEdit,
    NameInput {
        name: String,
    },
    /// Create a new group.
    NewGroup,
    AddSelectionToGroup {
        id: OrganizerNodeId,
    },
    Delete {
        id: OrganizerNodeId,
    },
    DragDropped(DragIdentifier),
    Dragging(DragIdentifier),
    AttributeSelected {
        attribute: DnaAttribute,
        id: OrganizerNodeId,
    },
}

/// Shorthands to send internal messages.
impl OrganizerMessage {
    pub(super) fn expand(id: OrganizerNodeId, expanded: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Expand { id, expanded })
    }

    pub(super) fn node_selected(id: OrganizerNodeId) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NodeSelected { id })
    }

    pub(super) fn node_hovered(id: OrganizerNodeId, hovered_in: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NodeHovered { id, hovered_in })
    }

    pub(super) fn key_hovered(key: DesignElementKey, hovered_in: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::KeyHovered { key, hovered_in })
    }

    pub(super) fn edit(id: OrganizerNodeId) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Edit { id })
    }

    pub(super) fn delete(id: OrganizerNodeId) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Delete { id })
    }

    pub(super) fn name_input(name: String) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NameInput { name })
    }

    pub(super) fn stop_edit() -> Self {
        Self::InternalMessage(OrganizerInternalMessage::StopEdit)
    }

    pub(super) fn element_selected(key: DesignElementKey) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::ElementSelected { key })
    }

    pub(super) fn add_selection_to_group(id: OrganizerNodeId) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::AddSelectionToGroup { id })
    }

    pub(super) fn new_group() -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NewGroup)
    }

    pub(super) fn dragging(key: DragIdentifier) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Dragging(key))
    }

    pub(super) fn drag_dropped(key: DragIdentifier) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::DragDropped(key))
    }

    pub(super) fn attribute_selected(attribute: DnaAttribute, id: OrganizerNodeId) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::AttributeSelected { attribute, id })
    }
}
