use super::{OrganizerNodeId, drag_drop_target::DragIdentifier};
use crate::keyboard_priority::PriorityRequest;
use ensnano_design::{
    elements::DesignElementKey,
    organizer::{
        element::OrganizerElement,
        tree::{GroupId, OrganizerTree},
    },
};
use iced::widget::text_input;
use std::collections::BTreeMap;

/// Public messages generated by an Organizer.
#[derive(Clone, Debug)]
pub enum OrganizerMessage<E: OrganizerElement> {
    InternalMessage(OrganizerInternalMessage<E>),
    Selection(Vec<DesignElementKey>, Option<GroupId>),
    Candidates(Vec<DesignElementKey>),
    ElementUpdate(Vec<BTreeMap<DesignElementKey, E>>),
    NewAttribute(E::Attribute, Vec<DesignElementKey>),
    /// Publishing a new organizer tree.
    NewTree(OrganizerTree<DesignElementKey>),
    /// A new group is created.
    NewGroup {
        group_id: GroupId,
        elements_selected: Vec<DesignElementKey>,
        new_tree: OrganizerTree<DesignElementKey>,
    },
    /// Taking or releasing keyboard priority.
    SetKeyboardPriority(PriorityRequest),
    /// Ask Iced application to focus on this element
    SetFocus(text_input::Id),
}

#[derive(Clone, Debug)]
pub enum OrganizerInternalMessage<E: OrganizerElement> {
    Expand {
        id: OrganizerNodeId<E::AutoGroup>,
        expanded: bool,
    },
    NodeSelected {
        id: OrganizerNodeId<E::AutoGroup>,
    },
    NodeHovered {
        id: OrganizerNodeId<E::AutoGroup>,
        hovered_in: bool,
    },
    KeyHovered {
        key: DesignElementKey,
        hovered_in: bool,
    },
    ElementSelected {
        key: DesignElementKey,
    },
    Edit {
        id: OrganizerNodeId<E::AutoGroup>,
    },
    StopEdit,
    NameInput {
        name: String,
    },
    /// Create a new group.
    NewGroup,
    AddSelectionToGroup {
        id: OrganizerNodeId<E::AutoGroup>,
    },
    Delete {
        id: OrganizerNodeId<E::AutoGroup>,
    },
    DragDropped(DragIdentifier<E::AutoGroup>),
    Dragging(DragIdentifier<E::AutoGroup>),
    AttributeSelected {
        attribute: E::Attribute,
        id: OrganizerNodeId<E::AutoGroup>,
    },
}

/// Shorthands to send internal messages.
impl<E: OrganizerElement> OrganizerMessage<E> {
    pub(super) fn expand(id: OrganizerNodeId<E::AutoGroup>, expanded: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Expand { id, expanded })
    }

    pub(super) fn node_selected(id: OrganizerNodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NodeSelected { id })
    }

    pub(super) fn node_hovered(id: OrganizerNodeId<E::AutoGroup>, hovered_in: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NodeHovered { id, hovered_in })
    }

    pub(super) fn key_hovered(key: DesignElementKey, hovered_in: bool) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::KeyHovered { key, hovered_in })
    }

    pub(super) fn edit(id: OrganizerNodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Edit { id })
    }

    pub(super) fn delete(id: OrganizerNodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Delete { id })
    }

    pub(super) fn name_input(name: String) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NameInput { name })
    }

    pub(super) fn stop_edit() -> Self {
        Self::InternalMessage(OrganizerInternalMessage::StopEdit)
    }

    pub(super) fn element_selected(key: DesignElementKey) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::ElementSelected { key })
    }

    pub(super) fn add_selection_to_group(id: OrganizerNodeId<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::AddSelectionToGroup { id })
    }

    pub(super) fn new_group() -> Self {
        Self::InternalMessage(OrganizerInternalMessage::NewGroup)
    }

    pub(super) fn dragging(key: DragIdentifier<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::Dragging(key))
    }

    pub(super) fn drag_dropped(key: DragIdentifier<E::AutoGroup>) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::DragDropped(key))
    }

    pub(super) fn attribute_selected(
        attribute: E::Attribute,
        id: OrganizerNodeId<E::AutoGroup>,
    ) -> Self {
        Self::InternalMessage(OrganizerInternalMessage::AttributeSelected { attribute, id })
    }
}
